### PR TITLE
Custom starting page option + start pages from 0

### PR DESCRIPTION
**Pull request by LebsterFace**
- Added custom starting page option
- Moved pages to start at 0
- Changed to triple equals
- Added semicolons

### CODE REVIEW

**Review by Juby210 — CHANGES_REQUESTED** [review]
please don't change code style, i will accept this if this would only add custom starting page.

**Comment by LebsterFace** [comment]
What about 0 indexed page numbers?

**Comment by Juby210** [comment]
it can stay

**Comment by LebsterFace** [comment]
Ok I have made the changes you requested, so will you accept?

**Review by Juby210 — APPROVED** [review]

**Pull request merged**
